include(FindPkgConfig)
PKG_CHECK_MODULES(PC_ZEROMQ "libzmq")

find_path(
    ZEROMQ_INCLUDE_DIR
    NAMES zmq.h
    HINTS ${PC_ZEROMQ_INCLUDEDIRS} ${PC_ZEROMQ_INCLUDE_DIRS}
)

find_library(
    ZEROMQ_LIBRARY
    NAMES zmq
    HINTS ${PC_ZEROMQ_LIBDIR} ${PC_ZEROMQ_LIBRARY_DIRS}
)

set(ZEROMQ_LIBRARIES ${ZEROMQ_LIBRARY})
set(ZEROMQ_INCLUDE_DIRS ${ZEROMQ_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ZEROMQ DEFAULT_MSG ZEROMQ_LIBRARY ZEROMQ_INCLUDE_DIR)
mark_as_advanced(ZEROMQ_LIBRARY ZEROMQ_INCLUDE_DIR)
